### ISSUE TITLE
datacube system check - empty config file

### ISSUE THREAD

**Issue by kpapap** [SARScripts/openeo_odc_driver#15]
When deploying, the odc “datacube system check” returns an empty line in the config file location. Can this be an issue that would prevent the deployment from working?

**Comment by pierocampa** [comment]
Hi @kpapap,
are you referring to #17 when you say that the deployment won't work, or what is it exactly?

**Comment by kpapap** [comment]
> Hi @kpapap, are you referring to #17 when you say that the deployment won't work, or what is it exactly?

Yes, I was referring to this issue. I was trying to figure out possible causes of the error and noticed that there was an empty line in the config file location of the database, thanks!
