### ISSUE TITLE
coherence calculation

### ISSUE THREAD

**Issue by jonathom** [SARScripts/openeo_odc_driver#2]
Just out of curiosity I wanted to ask about your coherence function:
https://github.com/SARScripts/openeo_odc_driver/blob/1a938a16ad5449014e37c83aaa8f20cc2e9c8e85/openeo_odc_driver.py#L1287

and following lines, e.g.:
https://github.com/SARScripts/openeo_odc_driver/blob/1a938a16ad5449014e37c83aaa8f20cc2e9c8e85/openeo_odc_driver.py#L1289

Coherence is typically a window function. I can see that you are looping through the pairs of days between reference and secondary images here, but could you point me to the lines where it is applied on an image window?
The calculation seems to happen on data in `self.partialResults`, but I couldn't figure out what it contains.
Thanks!

**Comment by clausmichele** [comment]
The coherence function is not perfect nor well defined yet, but this is what it currently does:
1. Find the date pairs corresponding to the required temporal baseline and loop over them
2. Compute the **complex coherence**, for real and imaginary part for each polarization

This process returns the complex coherence and therefore, to get the final result, we need to apply a couple of additional steps. The `aggregate_spatial_window `is applied afterwards and it's the window function you are mentioning (or also Multi-Look). Please check this process graph with all the necessary steps to get the coherence values:
https://editor.openeo.org/?server=https%3A%2F%2Fopeneo.eurac.edu&process=https%3A%2F%2Fraw.githubusercontent.com%2FSARScripts%2FSAR2Cube_use_cases%2Fmain%2Fprocess_graphs%2FSAR2Cube_coherence_timeseries_netCDF.json&discover=1

Maybe I could rename the process from coherence to complex_coherence to make it clearer.

**Comment by jonathom** [comment]
Thanks @clausmichele! That cleared things up.
> The calculation seems to happen on data in self.partialResults, but I couldn't figure out what it contains.

Here I was more aiming at the question "How are the preprocessing results stored?", i.e. what kind of file / collection of files lies behind the `SAR2Cube_L0_117_ASC_ST_2016_2020_IFG_LIA_DEM`? SNAP saves both the reference and secondary of a coregistration to a file _per pair_, that can't be very feasible if the reference is always the same, right? So do you extract the bands somehow?

**Comment by clausmichele** [comment]
The experimental process coherence is deprecated. It is possible to compute the coherence using standard openEO processes following this notebook: https://gitlab.inf.unibz.it/earth_observation_public/eurac-openeo-examples/-/blob/main/python/SAR2Cube_openEO_examples_coherence_boxcar.ipynb
