### ISSUE TITLE
Where to find datacube.conf

### ISSUE THREAD

**Issue by romeokienzler** [SARScripts/openeo_odc_driver#7]
I'm trying to setup [openeo_odc_driver](https://github.com/SARScripts/openeo_odc_driver) with ODC sandbox. Although I still don't know how to open ODC sandbox's data explorer endpoint, the [issue](https://github.com/opendatacube/cube-in-a-box/issues/60) is with them at the moment

But what I don't know is where to get the datacube.conf file from as described in [here](https://github.com/SARScripts/openeo_odc_driver#step-3)

Happy if you could shine some light on this

**Comment by clausmichele** [comment]
@romeokienzler I finalized the Docker setup and updated the README on the dev branch. Please try it and let me know if everything works as expected!
https://github.com/SARScripts/openeo_odc_driver/tree/dev

**Comment by romeokienzler** [comment]
Wow thanks @clausmichele will do asap!

**Comment by romeokienzler** [comment]
Hi @clausmichele 

I've proposed two changes in #8 - I don't think sudo is necessary and also the two ports seem to be http and not https ports

I'm getting an error on 'make index' but this might be due to bad wifi connection at the airport, will test again later...

**Comment by romeokienzler** [comment]
@clausmichele I re-ran make index and make explorer manually and now open-data-cube works on http://localhost:9001/

localhost:5001/collection returns a 404 though....

![image](https://user-images.githubusercontent.com/5694071/220996098-8acc42c5-702d-4359-828a-d7fef1f6b2bb.png)

**Comment by clausmichele** [comment]
@romeokienzler I think that there is just a typo, there's an `s` at the end which is missing:

`localhost:5001/collections` not `localhost:5001/collection`
